parameters:
    kch.bundle.pcc3.declarationToXml.transformer.declaration.class: KCH\PCC3\Deklaracja

services:
    kch.bundle.pcc3.declarationToXml.transformer:
        class: KCH\Bundle\PCC3Bundle\Service\DeclarationToXmlTransformer
        arguments: [%kch.bundle.pcc3.declarationToXml.transformer.declaration.class%]

    kch.bundle.pcc3.xmlToDeclaration.transformer:
        class: KCH\Bundle\PCC3Bundle\Service\XmlToDeclarationTransformer
        arguments: [%kch.bundle.pcc3.declarationToXml.transformer.declaration.class%]